# Generated by Django 3.1 on 2024-05-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendors',
            name='average_response_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='fulfillment_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='on_time_delivery_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='quality_rating_avg',
            field=models.FloatField(default=0.0),
        ),
    ]
